spring:
  application:
    name: StallApp
  jpa:
    show-sql: true
    hibernate:
      ddl.auto: create
    properties:
      hibernate:
        cache:
          use_second_level_cache: true
        region:
          factory_class: jcache
        javax:
          cache:
            provider: org.ehcache.jsr107.EhcacheCachingProvider
  datasource:
    url: jdbc:h2:mem:msdb
    username: root
    password: root
    driver-class-name: org.h2.Driver
  h2:
    console.enabled: true
  kafka:
    bootstrap-servers: localhost:9092
    listener:
      idle-between-polls: 5

logging:
  level:
    org.springframework: debug
    org.springframework.cache: debug
    com.learning.stall.controller: debug

management:
  endpoints:
    web:
      exposure:
        include: beans, metrics